# Generated by Django 2.0.2 on 2018-03-01 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeForProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=20)),
                ('cast_type', models.CharField(choices=[('str', 'Строка'), ('int', 'Целое число'), ('color', 'Цвет'), ('float', 'Дробное число')], max_length=10)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.AddField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='product_variant',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.ProductVariant'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='value',
            field=models.CharField(blank=True, default='n/a', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='attribute',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.AttributeForProduct'),
        ),
    ]
