# Generated by Django 2.0.2 on 2018-03-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180301_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='attribute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.AttributeForProduct'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='productattributes',
            name='product_variant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.ProductVariant'),
        ),
    ]
