# Generated by Django 2.0.2 on 2018-03-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttocatalog',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Catalog'),
        ),
        migrations.AddField(
            model_name='producttocatalog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product'),
        ),
    ]
