# Generated by Django 2.0.2 on 2018-03-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180302_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogparent',
            name='child',
        ),
        migrations.RemoveField(
            model_name='catalogparent',
            name='parent',
        ),
        migrations.DeleteModel(
            name='CatalogParent',
        ),
    ]
