# Generated by Django 2.0.2 on 2018-03-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_catalog_catalogtoparent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogtoparent',
            name='child',
        ),
        migrations.RemoveField(
            model_name='catalogtoparent',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='CatalogToParent',
        ),
    ]
