# Generated by Django 2.0.2 on 2018-03-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('code', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='attributeforproduct',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attributeforproduct',
            name='title',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='title',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='title',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AddField(
            model_name='producttag',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Tag'),
        ),
        migrations.AddField(
            model_name='catalogtag',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Catalog'),
        ),
        migrations.AddField(
            model_name='catalogtag',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Tag'),
        ),
    ]
