# Generated by Django 2.0.2 on 2018-03-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_producttocatalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productclass',
            options={'verbose_name': 'Вид товара', 'verbose_name_plural': 'Виды товаров'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Разновидность товара', 'verbose_name_plural': 'Разновидность товара'},
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='ink',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='variantimage',
            old_name='ink',
            new_name='link',
        ),
    ]
